Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
Forbidden (Origin checking failed - https://192.168.1.196 does not match any trusted origins.): /admin/login/
WARNING:django.security.csrf:Forbidden (Origin checking failed - https://192.168.1.196 does not match any trusted origins.): /admin/login/
Forbidden (Origin checking failed - https://192.168.1.196 does not match any trusted origins.): /admin/login/
WARNING:django.security.csrf:Forbidden (Origin checking failed - https://192.168.1.196 does not match any trusted origins.): /admin/login/
Not Found: /import/
WARNING:django.request:Not Found: /import/
Forbidden (Origin checking failed - https://192.168.1.196 does not match any trusted origins.): /admin/login/
WARNING:django.security.csrf:Forbidden (Origin checking failed - https://192.168.1.196 does not match any trusted origins.): /admin/login/
WARNING:django.request:Forbidden (Permission denied): /admin/auth/user/
Traceback (most recent call last):
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 1996, in changelist_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING:django.request:Forbidden (Permission denied): /admin/auth/user/2/change/
Traceback (most recent call last):
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 1962, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 1818, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 1845, in _changeform_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING:django.request:Forbidden (Permission denied): /admin/auth/user/
Traceback (most recent call last):
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\srv\Daily_Report_Internal\.venv\lib\site-packages\django\contrib\admin\options.py", line 1996, in changelist_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING:django.request:Not Found: /admin/ ‚É
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
